### ISSUE TITLE
Missing dependency on `rich`

### ISSUE THREAD

**Issue by bryanwweber** [conda-forge/dask-ctl-feedstock#3]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Running `mamba install dask-ctl` works great, but `daskctl cluster list` immediately after installing results in:

```python
Traceback (most recent call last):
  File "/opt/conda/bin/daskctl", line 6, in <module>
    from dask_ctl.cli import daskctl
  File "/opt/conda/lib/python3.9/site-packages/dask_ctl/cli.py", line 6, in <module>
    from rich import box
ModuleNotFoundError: No module named 'rich'
```

Once I install `rich` manually, everything works great! 🎉 

I'd be happy to submit a PR if you want 😄

**Comment by jacobtomlinson** [comment]
Thanks for catching this @bryanwweber
